# container with R installed and with R entrypoint
# build with: docker build <path_to_dockerfile> --tag='phil-r2'
# run with: docker run -it phil-r2
# after exit find container name with: docker ps -a
# start existing container: docker start -i <container_name>

FROM phil-r

# set command to run on startup
CMD ["R"]
