help:
	@echo Makefile commands:
	@echo
	@echo help: print this help message and exit
	@echo build: build the docker image
	@echo run: run the docker image

build:
	docker build . --tag='phil-r'

run:
	docker run -it phil-r
